Makefile, book/src/examples/how_can_i/aggregate.py, book/src/examples/how_can_i/apply_window_functions.py, book/src/examples/how_can_i/conditionally_apply.py, book/src/examples/how_can_i/groupby.py, book/src/examples/how_can_i/parse_dates.py, book/src/examples/how_can_i/process_strings.py, book/src/examples/how_can_i/split_apply_combine.py, book/src/examples/how_can_i/use_custom_functions.py, book/src/examples/how_can_i/use_custom_functions_1.py, book/src/examples/how_can_i/use_custom_functions_2.py, book/src/examples/how_can_i/use_custom_functions_3.py, book/src/examples/lazy_chapter/data_head.py, book/src/examples/lazy_chapter/predicate_pushdown_0.py, book/src/examples/lazy_chapter/predicate_pushdown_1.py, book/src/examples/lazy_chapter/projection_pushdown_0.py, book/src/how_can_i/aggregate.md, book/src/how_can_i/intro.md, book/src/how_can_i/process_strings.md, book/src/lazy_polars/intro.md, book/src/reference.md, create_data.py, macro_bench/polars_query_cheap.py, macro_bench/polars_query_exp.py, macro_bench/polars_query_exp2.py, micro_bench/csv_read.py, micro_bench/groupby_polars.py, micro_bench/join.py, micro_bench/plot_results.py, requirements.txt
Following https://github.com/ritchie46/polars/pull/430.
Should `$(SHELL) download.sh` be added to the `make data` target? Otherwise, `make run` does not work.
Locally, `how_can_i.split_apply_combine` needs a small workaround for the shadowed `range`, while `how_can_i.use_custom_functions_3` errors on `assertion failed: (offset + length) <= self.len()`. I presume these have nothing to do with the naming changes.
=> Track pypolars rename

.github/workflows/docs.yaml, Dockerfile
Removed the `Rust` step by using a pre-compiled version of the `mdBook`.
Also bumped the `Python` version to 3.8.
=> Modified the CI

.github/workflows/docs.yaml, .github/workflows/tests.yaml
What the single commit message says.
=> Rolled back ghp-import

.github/workflows/docs.yaml
Added `sudo` to allow writing in the `/usr/bin` folder, and that should do it. My bad, let that one slip.
=> /usr/bin rights

Makefile, README.md, user_guide/src/SUMMARY.md, user_guide/src/examples/df_manipulations/__main__.py, user_guide/src/examples/df_manipulations/add_column.py, user_guide/src/examples/df_manipulations/casting.py, user_guide/src/examples/df_manipulations/dataset.py, user_guide/src/examples/df_manipulations/drop_column.py, user_guide/src/examples/df_manipulations/rename_column.py, user_guide/src/howcani/df/common-manipulations.md
Initial commit to add examples and docs around Dataframe manipulations
=> WIP: df manipulations examples

user_guide/src/dsl/intro.md
=> Fix display of code examples

user_guide/src/dsl/intro.md, user_guide/src/howcani/apply/udfs.md, user_guide/src/howcani/df/common-manipulations.md, user_guide/src/howcani/interop/arrow.md, user_guide/src/howcani/intro.md, user_guide/src/indexing.md, user_guide/src/introduction.md, user_guide/src/performance/intro.md
While going through the docs, I spotted a few typos, etc. These are my suggested edits, ranging from simple punctuation to a few suggestions to improve legibility. Hope you find them useful and if you don't agree with them, of course, feel free to ignore them.
Note: I have not had the time/tried to build the docs locally, but have not touched any of the code.
=> minor corrections: typos, etc.

user_guide/src/examples/df_manipulations/__main__.py, user_guide/src/examples/df_manipulations/add_column.py, user_guide/src/examples/df_manipulations/casting.py, user_guide/src/howcani/df/common-manipulations.md
=> fix output in df_manipulations

user_guide/src/examples/predicate_pushdown/__main__.py, user_guide/src/examples/predicate_pushdown/snippet1.py, user_guide/src/examples/predicate_pushdown/snippet2.py, user_guide/src/optimizations/lazy/predicate-pushdown.md
> If we were to run this query above, nothing would happen
The document says the snippet will not execute until `.collect` or `.fetch` is run, so the snippet should not contain any `.fetch` method.
Also the document use object `reddit`, but it is not in the snippet. To follow other snippet naming convention, I modify document to `q1` and `q2`
=> fix Predicate pushdown doc

user_guide/src/quickstart/intro.md
Purpose of PR:
* fix bug in `scan_csv` in the quickstart (example doesn't work cause data is stored in HTTP)
* Format all code snippets with black
* Avoid reassigning `df`
Thanks for making the Polars book.  It's a great way to get users started with the lib!!
=> Fix bug in scan_csv example

user_guide/src/coming_from_pandas.md
Just swapping a column name in a polars example to match the pandas example better. Also making a sentence clearer to read (in my opinion).
=> Minor corrections in coming_from_pandas.md

user_guide/preprocessor/replace.py, user_guide/src/dsl/contexts.md, user_guide/src/dsl/numpy.md, user_guide/src/timeseries/intro.md
=> fix some issues

user_guide/src/coming_from_pandas.md, user_guide/src/indexing.md, user_guide/src/timeseries/intro.md
Fixing some typos in the documentation.
=> Fix typos.

user_guide/src/coming_from_pandas.md
current version causes TypeError
=> missing .loc added

user_guide/src/dsl/contexts.md, user_guide/src/dsl/folds.md, user_guide/src/dsl/groupby.md
=> Fix user guide errors from #141

user_guide/src/dsl/list_context.md, user_guide/src/examples/time_series/__main__.py, user_guide/src/examples/time_series/dynamic_groupby.py, user_guide/src/examples/time_series/parsing_dates.py, user_guide/src/examples/time_series/resampling_example.py, user_guide/src/timeseries/intro.md, user_guide/src/timeseries/parsing_dates_times.md, user_guide/src/timeseries/resampling.md
@braaannigan note that I added a few trailing comma's in the code snippets to enforce `black` to explode the snippets.
I also renamed two variables because the lines were so long that they were out of screen.
=> small fmt and typos (#148)

Makefile, user_guide/src/SUMMARY.md, user_guide/src/coming_from_pandas.md, user_guide/src/examples/missing_data/__main__.py, user_guide/src/examples/missing_data/fill_strategies.py, user_guide/src/examples/missing_data/missing_types.py, user_guide/src/examples/time_series/__main__.py, user_guide/src/examples/time_series/parsing_dates.py, user_guide/src/missing_data.md, user_guide/src/timeseries/parsing_dates_times.md
Docs page on missing values
Note: for the is_null and null_count parts I based the stuff on validity bitmaps on the Arrow specification docs. Please read through and let me know if it reflects the reality of the Rust Arrow implementation.
=> Missing values

user_guide/src/coming_from_pandas.md
=> Missing value link is 404

user_guide/src/coming_from_pandas.md
=> Add missing comma

.gitattributes
I've noticed a couple people assume this repo is literally just jupyter notebooks.
Tell linguist to sit down.
=> Tell linguist to ignore languages

Makefile, user_guide/src/introduction.md
This also sneaks in removing old reference guide Makefile commands + highlighting Polars. I can move this to a new PR if you'd prefer.
=> Add TPCH results link and some Makefile corrections

user_guide/src/howcani/timeseries/resampling.md
related #164
I can dig for more broken links if needed.
=> Fix temporal groupby link

user_guide/src/howcani/selecting_data/selecting_data_expressions.md
Right now the code is not match the document.
Ref: https://pola-rs.github.io/polars-book/user-guide/howcani/selecting_data/selecting_data_expressions.html#selecting-rows-with-the-filter-method
=> docs: fix some code position error

README.md, user_guide/src/SUMMARY.md, user_guide/src/howcani/io/aws.md, user_guide/src/howcani/io/csv.md, user_guide/src/howcani/io/json.md, user_guide/src/howcani/io/parquet.md, user_guide/src/performance/strings.md, user_guide/tabbed-code-blocks.js
- Update a bunch of the "How Can I" pages to include rust examples
- Add JSON/NdJson examples for py + rust.
=> feat(howcani): add rust examples to howcani

user_guide/src/SUMMARY.md, user_guide/src/examples/multiprocessing/example1.py, user_guide/src/examples/multiprocessing/example2.py, user_guide/src/examples/multiprocessing/recommendation.py, user_guide/src/howcani/multiprocessing.md
=> Add multiprocessing guide

user_guide/src/datatypes.md
- Fix internal representation units of datetime to be microseconds 
- Add Binary 
- Re-order dtypes to have Object with List and Struct
=> Small changes to datatypes

user_guide/src/examples/time_series/resampling_example.py
I got an error when I tried to `make serve` the book locally. It looked like the upsampling example was outdated. After the adjustment no errors are raised and the book is created.
=> updated upsampling example

user_guide/src/dsl/custom_functions.md, user_guide/src/examples/time_series/__main__.py, user_guide/src/examples/time_series/parsing_dates.py, user_guide/src/howcani/timeseries/selecting_dates.md, user_guide/src/indexing.md, user_guide/src/optimizations/lazy/projection-pushdown.md, user_guide/src/quickstart/quick-exploration-guide.md
Here's how the rendered docs look:
This is to address what I brought up in https://github.com/pola-rs/polars/issues/6282
Also fixing some assorted typos while I'm here, hope it's OK
=> Add example of filtering with negative dates

user_guide/src/coming_from_pandas.md
=> conform syntax to pep-8

user_guide/src/examples/time_series/parsing_dates.py
closes #239 
Now it looks like this:
=> time series examples show wrong df 

user_guide/src/coming_from_pandas.md, user_guide/src/dsl/custom_functions.md, user_guide/src/dsl/list_context.md, user_guide/src/examples/conditionally_apply/lazy.py, user_guide/src/examples/df_manipulations/add_column.py, user_guide/src/examples/df_manipulations/casting.py, user_guide/src/examples/expressions/list_row_wise.rs, user_guide/src/examples/group_statistics/dataset.py, user_guide/src/examples/group_statistics/snippet2.py, user_guide/src/examples/groupby_dsl/dataset.py, user_guide/src/examples/groupby_dsl/groupby.rs, user_guide/src/examples/missing_data/fill_strategies.py, user_guide/src/examples/strings/snippet1.py, user_guide/src/examples/strings_performance/snippet1.py, user_guide/src/examples/strings_performance/snippet2.py, user_guide/src/examples/testing/schema_assert.py, user_guide/src/examples/time_series/cast_date_to_string.py, user_guide/src/examples/timestamps/snippet.py, user_guide/src/howcani/df/aggregate.md, user_guide/src/howcani/io/postgres.md, user_guide/src/performance/strings.md, user_guide/src/quickstart/quick-exploration-guide.md
When trying out this snippet I receive a warning that 'with_column' is deprecated:
```
DeprecationWarning: `with_column` has been deprecated in favor of `with_columns`. This method will be removed in version 0.17.0
```
This pull request adds an 's' to 'with_column' to use the newer 'with_columns' method.
=> Change with_column to with_columns

Makefile, user_guide/src/SUMMARY.md, user_guide/src/examples/sql/__main__.py, user_guide/src/examples/sql/sql_1.py, user_guide/src/examples/sql/sql_2.py, user_guide/src/sql.md
@ritchie46 
Partially addresses https://github.com/pola-rs/polars/issues/6984
look forward to any feedback on this
=> add SQL section in the Polars book

user_guide/src/howcani/timeseries/resampling.md
=> fix upsample example

user_guide/src/examples/expressions/fold_1.py, user_guide/src/examples/expressions/fold_2.py, user_guide/src/examples/time_series/parsing_dates.py, user_guide/src/notebooks/introduction_polars-py.ipynb
Code cell was formatted as markdown
=> fix code formatted as markdown

user_guide/src/dsl/expressions.md
This is a pull request in response to the following Issue.
https://github.com/pola-rs/polars-book/issues/251
=> fix expression example of rust(#251)

user_guide/src/dsl/groupby.md, user_guide/src/examples/quickstart/__main__.py, user_guide/src/howcani/io/aws.md, user_guide/src/howcani/io/read_db.md, user_guide/src/optimizations/lazy/other-optimizations.md, user_guide/src/optimizations/lazy/projection-pushdown.md, user_guide/src/quickstart/quick-exploration-guide.md, user_guide/src/time-series.md
Update read DB page to change to pl.read_database and discuss engines
=> update read DB page

user_guide/src/dsl/custom_functions.md, user_guide/src/dsl/groupby.md, user_guide/src/examples/groupby_dsl/groupby.rs, user_guide/src/introduction.md
Fixes some typos and makes the layout of a python function a touch more readable.
=> Fix a few typos

API_REFERENCE_LINKS.yaml, docs/src/python/user-guide/expressions/casting.py, docs/user-guide/expressions/casting.md, requirements.txt
Adds a section on casting
- Explaining strict parameter
- Basic conversions and what happens in case of an overflow
- Date time parsing and to string
=> Add Section on Casting

API_REFERENCE_LINKS.yaml, docs/snippets/rust_lazy_clone_warning.md, docs/src/python/user-guide/expressions/strings.py, docs/src/rust/getting-started/joins.rs, docs/src/rust/getting-started/reading-writing.rs, docs/src/rust/getting-started/series-dataframes.rs, docs/src/rust/user-guide/concepts/contexts.rs, docs/src/rust/user-guide/concepts/lazy-vs-eager.rs, docs/src/rust/user-guide/expressions/aggregation.rs, docs/src/rust/user-guide/expressions/folds.rs, docs/src/rust/user-guide/expressions/lists.rs, docs/src/rust/user-guide/expressions/user-defined-functions.rs, docs/src/rust/user-guide/expressions/window.rs, docs/src/rust/user-guide/io/csv.rs, docs/stylesheets/extra.css, docs/user-guide/expressions/aggregation.md, docs/user-guide/expressions/numpy.md, docs/user-guide/expressions/strings.md, docs/user-guide/expressions/user-defined-functions.md, docs/user-guide/installation.md, docs/user-guide/io/aws.md, docs/user-guide/io/database.md, docs/user-guide/io/json_file.md, docs/user-guide/io/parquet.md, requirements.txt, scripts/macro.py
We currently don't really consistenly cover which feature flags should be activated to run the code (especially for Rust examples). This might confuse users as the examples won't run for them. 
This PR includes:
- Include feature flags in documentation
- Add Lazy feature in installation section (globally) as it is required by almost all examples
- Better docstrings for macro.py
- Move imports inside code segments
- Minor Fixes Rust code
- An extra page for strings
=> Feature Flags

docs/stylesheets/extra.css
In dark mode the custom background color for feature flags looks ugly, this PR changes it to something more in line with the rest
=> Dark mode Feature flag color

mkdocs.yml
It would be helpful to know how users interact with our User Guide using Google Analytics. This way we:
-  Are more guided on what to improve / add based on usage
-  Know if the intended 'learning paths' are followed or if people find the guide setup confusing
Curious about your thoughts @ritchie46
=> Add GA support

docs/index.md
Following from https://github.com/pola-rs/polars/pull/8314
=> Update H2O.ai's benchmark link.

mkdocs.yml
See https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/?h=light+dark#system-preference
Resolves #325
Tested locally and it works
=> Auto detect dark/light mode preference

docs/src/python/user-guide/transformations/time-series/rolling.py, docs/user-guide/transformations/time-series/rolling.md
Latest release (notice how the output is the original df, not yearly average):
Here:
=> fixup groupby_dynamic example

docs/user-guide/expressions/aggregation.md
=> Link to UDF page

docs/getting-started/intro.md, mkdocs.yml
@ritchie46 
this should hopefully fix the issue with the deployment.
it looks like the base path for the snippets should be declared in the mkdocs.yml file and not be relative to the current path
=> fix path issue that prevents deployment

docs/user-guide/concepts/lazy-vs-eager.md
=> fix documentation typo

docs/src/python/user-guide/expressions/window.py, docs/user-guide/expressions/window.md
Update for the window functions
=> update window functions for 0.18

docs/user-guide/concepts/data-types.md, docs/user-guide/concepts/expressions.md, docs/user-guide/concepts/lazy-vs-eager.md, docs/user-guide/expressions/aggregation.md, docs/user-guide/expressions/casting.md, docs/user-guide/expressions/folds.md, docs/user-guide/expressions/functions.md, docs/user-guide/expressions/null.md
I just saw a few more typos and thought I could update them quickly. 
Happy to do more in the future if I see them, but if you prefer not just let me know that too. :)
=> Additional typo fixes in the documentation

docs/src/python/getting-started/series-dataframes.py
Resolves https://github.com/pola-rs/polars/issues/9628
=> Add missing datetime import

API_REFERENCE_LINKS.yaml, docs/src/python/user-guide/expressions/structs.py, docs/user-guide/expressions/structs.md, docs/user-guide/expressions/user-defined-functions.md, mkdocs.yml
Closes https://github.com/pola-rs/polars-book/issues/329.
Open to feedback.
=> Struct Data Type tutorial

.gitignore, Makefile, README.md, package-lock.json, package.json
adds a makefile to easily setup requirements, serve, and lint. 
I was considering using [just](https://github.com/casey/just) instead of make, but didn't want to add another build tool without making sure that it was ok first.
=> build: add makefile

docs/user-guide/expressions/lists.md
Just some minor things I missed while filing https://github.com/pola-rs/polars-book/pull/351.
=> Fix typos and stylize new List tutorial

docs/src/python/getting-started/series-dataframes.py, docs/user-guide/transformations/joins.md
Resolves [#9915](https://github.com/pola-rs/polars/issues/9915)
=> Add summary of join types, and include summary sentence in anti-join subsection.

docs/src/python/user-guide/concepts/contexts.py, docs/src/rust/getting-started/series-dataframes.rs, docs/user-guide/expressions/folds.md
I just read through the book and found a couple minor imperfections.
=> Minor typos/touchups.

docs/user-guide/lazy/schemas.md
Fixes https://github.com/pola-rs/polars-book/issues/359
Update exception from lazy execution
=> Fix lazy exception

mkdocs.yml
Addresses any warnings on startup
=> Clean up mkdocs config
