user_guide/src/indexing.md
This simply removes two lines that are duplicated in the `Indexing` page.
=> Remove duplicated lines in Indexing page

user_guide/src/coming_from_pandas.md
This pull request makes the explanation of the section "Column assignment based on predicate" easier to understand, and also fixes a typo in the beginning of the sentence. It also fixes typos on the section name and in it's text body.
=> Fixes typos in Coming From Pandas

user_guide/src/examples/time_series/parsing_dates.py, user_guide/src/timeseries/parsing_dates_times.md, user_guide/src/timeseries/selecting_dates.md, user_guide/src/timeseries/temporal_groupby.md
Fixes offsets, I messed up in previous PR.
Also uses pythons `datetime.datetime` in favor of `pl.datetime`. @braaannigan I changed the comparisson code a bit, because using pythons native `datetime, date` and `timedelta` is idiomatic.
=> fix offsets and use datetime.datetime

user_guide/src/coming_from_pandas.md
Fixes #177
There was an additional dead link in there as well (second refererence to `selection_data`).
=> Fix dead links to selecting_data and missing_data

user_guide/src/dsl/expressions.md
Fixing two cases where the dataframe is modified and stored as `out`, but the original `df` is printed.
=> fix printing wrong dataframe

user_guide/src/quickstart/intro.md
Getting the correct feature-flags for dependencies can be an unnecessary roadblock for user onboarding, so it'd be awesome to have the necessary `[dependencies]` located nearby the Rust example
Having it be a codeblock doesn't seem ideal, so I'm open to ideas on where this could live on the page
=> Add Cargo.toml dependencies to quickstart

user_guide/src/examples/missing_data/fill_strategies.py
The example in the docs is
```
shape: (3, 2)
┌──────┬─────────┐
│ col1 ┆ col2    │
│ ---  ┆ ---     │
│ i64  ┆ str     │
╞══════╪═════════╡
│ 1    ┆ 1       │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 2    ┆ forward │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 3    ┆ 3       │
└──────┴─────────┘
```
which looks a bit odd - I guess this was meant to be `strategy="forward"`?
=> DOC specify strategy in fill_null

user_guide/src/dsl/api.md
Original Python link in the current User Guide for the Expressions API at https://pola-rs.github.io/polars-book/user-guide/dsl/api.html
https://pola-rs.github.io/polars/py-polars/html/reference/expression.html => 404
Correct link should be:
https://pola-rs.github.io/polars/py-polars/html/reference/expressions/index.html
=> Fix broken link for Python in Expressions API page

user_guide/src/examples/expressions/expressions.rs
https://github.com/pola-rs/polars/pull/4315
Supported updates to `std` and `var` methods that added ddof argument.
=> Added ddof argument to Rust code examples on the "Expressions" page

user_guide/src/quickstart/intro.md
issue #203 
- I fixed the "Lazy quick start" on the "Getting started" page.
I moved the explanation about `Cargo.toml` out of codeblock.
> I see. You had to use `text` because `tabbed-blocks` in `mdbook` does not support `toml`.
> 
> #199
> 
> > Having it be a codeblock doesn't seem ideal, so I'm open to ideas on where this could live on the page
> 
> It may be a good idea to follow the description in the "json.md" file.
> 
> https://pola-rs.github.io/polars-book/user-guide/howcani/io/json.html#note-about-rust-usage [user_guide/src/howcani/io/json.md](https://github.com/pola-rs/polars-book/blob/7490a9982073397025f1a5e589a20a077e1e5aba/user_guide/src/howcani/io/json.md)
=> Fix the "Lazy quick start" on the "Getting started" page

user_guide/src/examples/groupby_dsl/snippet5.py, user_guide/src/examples/groupby_dsl/snippet6.py, user_guide/src/examples/groupby_dsl/snippet7.py
https://pola-rs.github.io/polars-book/user-guide/dsl/groupby.html#sorting
In the code example on the above page, the "youngest" and "oldest" results are reversed because the `revese` option of `sort` is not specified.
https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.DataFrame.sort.html#polars.DataFrame.sort
=> Fixed sort option in "GroupBy" python code

user_guide/src/howcani/multiprocessing.md
https://github.com/pola-rs/polars-book/pull/197#issuecomment-1295766655
Fixed relative paths of include codes in "multiprocessing guide".
It now renders the code correctly.
=> Fixed relative paths of include codes in "multiprocessing guide"

user_guide/src/howcani/io/postgres.md
Just a tiny typo in the postgres markdown.
Should resolve #174 as the other typo has been already fixed.
=> fix typo in postgres markdown (#174)

user_guide/src/howcani/data/strings.md
old link was using outdated page anchor reference and leading to 404, new link works
=> fix link to `str` namespace

user_guide/src/quickstart/intro.md
small change: created tabblocks on the quickstart page for rust, python and nodejs. fits the design of the book better.
=> created tabblocks to better align with design

user_guide/src/optimizations/lazy/projection-pushdown.md
issue: https://github.com/pola-rs/polars-book/issues/201
Thanks!  https://github.com/pola-rs/polars/pull/5624
=> fix the code path in projection-pushdown

user_guide/src/dsl/expressions.md, user_guide/src/dsl/folds.md, user_guide/src/howcani/data/timestamps.md, user_guide/src/howcani/df/aggregate.md, user_guide/src/howcani/missing_data.md, user_guide/src/howcani/timeseries/parsing_dates_times.md, user_guide/src/howcani/timeseries/temporal_groupby.md, user_guide/src/quickstart/quick-exploration-guide.md
Various links to the API reference site are currently broken.
This change updates the URLs from the `section.html#subsection` pattern to the new `section/subsection.html` pattern.
Additionally, it standardizes the use of `POLARS_PY_REF_GUIDE` across the codebase by replacing occurrences of https://pola-rs.github.io/polars/py-polars/html/reference with the `POLARS_PY_REF_GUIDE` shorthand.
=> Fix broken links to API reference site

user_guide/src/quickstart/intro.md
Attempting to compile the Rust [Lazy quick start](https://pola-rs.github.io/polars-book/user-guide/quickstart/intro.html#lazy-quick-start) example currently results in an error. Importing std::io::Cursor fixes the issue.
=> Fix missing Cursor import in Rust Lazy quick start

user_guide/src/examples/expressions/apply_function.rs, user_guide/src/examples/expressions/contexts.rs, user_guide/src/examples/expressions/expressions.rs, user_guide/src/examples/expressions/fold.rs, user_guide/src/examples/expressions/list_row_wise.rs, user_guide/src/examples/expressions/map_function.rs, user_guide/src/examples/expressions/window.rs, user_guide/src/howcani/io/csv.md, user_guide/src/howcani/io/json.md, user_guide/src/howcani/io/parquet.md, user_guide/src/notebooks/introduction_polars-rs.ipynb, user_guide/src/performance/strings.md
There are outdated versions of the `df!` macro in several places in the book.
For instance on this page: https://pola-rs.github.io/polars-book/user-guide/dsl/expressions.html
Latest `df!` macro documentation: https://pola-rs.github.io/polars/polars/frame/struct.DataFrame.html#using-a-macro
```rust
let df = df! [
"keys" => ["a", "a", "b"],
"values" => [10, 7, 1],
]?;
```
```rust
let df = df! (
"keys" => &["a", "a", "b"],
"values" => &[10, 7, 1],
)?;
```
=> Update df macro usage

user_guide/src/howcani/data/timestamps.md
The chrono strptime isn't quite the same as the Python one https://github.com/chronotope/chrono/issues/945 , so I'm suggesting to link to the chrono docs instead
=> docs(python): Reference chrono strftime instead of strftime.org

user_guide/src/howcani/io/json.md
There's a typo in the How can I page about JSON. 
It seems that the text was copypasted from the page about Parquet
=> fix parquet->json typo

user_guide/src/examples/df_manipulations/__main__.py, user_guide/src/examples/time_series/resampling_example.py
fairly confident these were meant to be `strategy="forward"`? else it looks like this
```
shape: (13, 3)
┌─────────────────────┬─────────┬────────┐
│ time                ┆ groups  ┆ values │
│ ---                 ┆ ---     ┆ ---    │
│ datetime[μs]        ┆ str     ┆ f64    │
╞═════════════════════╪═════════╪════════╡
│ 2021-12-16 00:00:00 ┆ a       ┆ 1.0    │
│ 2021-12-16 00:15:00 ┆ forward ┆ null   │
│ 2021-12-16 00:30:00 ┆ a       ┆ 2.0    │
│ 2021-12-16 00:45:00 ┆ forward ┆ null   │
│ ...                 ┆ ...     ┆ ...    │
│ 2021-12-16 02:15:00 ┆ forward ┆ null   │
│ 2021-12-16 02:30:00 ┆ a       ┆ 6.0    │
│ 2021-12-16 02:45:00 ┆ forward ┆ null   │
│ 2021-12-16 03:00:00 ┆ a       ┆ 7.0    │
└─────────────────────┴─────────┴────────┘
```
as opposed to
```
In [7]: …
```
=> fix fill_null("forward")

user_guide/src/coming_from_pandas.md
To be fair to pandas, one should take advantage of `usecols` which makes the pandas and polars code more comparable.
It is still evident that polars is DRYer, as it doesn't force the user to explicitly note which columns to load.
=> Make use of `usecols` in pandas

user_guide/src/howcani/missing_data.md, user_guide/src/howcani/timeseries/temporal_groupby.md, user_guide/src/notebooks/introduction_polars-py.ipynb
- Fixes typos in variable names
- Removes redundant code cell in a notebook
=> Fix typos and remove redundant code cells

user_guide/src/howcani/interop/numpy.md
**Summary** 
Small clarification in Numpy documentation
**Features**
Changed "It can yield" to "This can lead" -- more descriptive and no initial confusion about generators `yield`
**Test Plan**
No other changes than markdown, so assuming no testing needed.
=> Clarified wording in How Can I / Numpy

user_guide/src/dsl/expressions.md
`Arc` stands for Atomically Reference Counted, see [Atomically Reference Counted](https://doc.rust-lang.org/std/sync/struct.Arc.html).
=> Incorrect acronym for 'Arc' type

CONTRIBUTING.md
small change to remove the confusion around pre-commit. as there is no pre-commit config yaml, contributors can use `make fmt` to format there code before committing.
=> removed usage of pre-commit and replaced with make fmt

user_guide/src/examples/expressions/fold.rs
This PR 
- Since 0.27.1, `polars::prelude::fold_exprs` expected an `Fn` that returns `Result<Option<Series>, PolarsError>` instead of `Result<Series, PolarsError>`.
- `Some()` had been added to the Rust Examples of "Manual Sum" and "Conditional" to follow this new signature.
This PR addresses #287 .
=> FIX Updated 2 Rust examples to follow 0.27.1+ `fold_exprs` function signature

mkdocs.yml, overrides/404.html
fix #305 
Not really a complete fix as old urls with paths that don't exist anymore still won't work. But this will at least ensure that all the assets (javascript, css, images) load fine and a 404 page is shown. 
In the current situation the site_url is empty and all assets are being loaded from root (https://pola-rs.github.io/) (in case of a non-existent link), but the user guide is on a subdomain (https://pola-rs.github.io/polars-book) hence the weird page.
You can observe the behavior difference:
- [https://c-peters.github.io/polars-book/does/not/exist](https://c-peters.github.io/polars-book/does/not/exist) returns valid 404
- [https://pola-rs.github.io/polars-book/does/not/exist](https://pola-rs.github.io/polars-book/does/not/exist) returns only the HTML, the assets load from the …
=> Set site root

.github/workflows/deploy.yaml
For forks it is useful to work from feature branches. However currently when you work on a non-master branch there is no way to deploy the fork in your own repository since the github actions are defined to deploy on master/main branches only. This PR adds a manual trigger allowing you to deploy manually from non-master branches.
The local development server of mkdocs is slightly different (e.g. path handling).  Deploying your fork on a feature branch is useful to test if everything is working.
=> Allow deployment from non-master branch for forks

docs/src/python/user-guide/expressions/window.py, docs/src/rust/user-guide/expressions/window.rs
fix #309 
Instead of sorting both columns independently, sort_by sorts them together fixing the example
=> fix window example

.github/workflows/deploy.yaml, Contributing.md, mkdocs.yml, scripts/people.py
Uses [mkdocs hooks](https://www.mkdocs.org/user-guide/configuration/#hooks) to run the `scripts/people.md` on startup.
Then it's a bit easier for new contributors. 
The time to generate `people.md` is negligible so I don't think it's a problem to always run it, but I get why some people might not agree with having this as a hook.
=> People hook

docs/user-guide/expressions/lists.md
Replace all occurrences of `arr.eval` and `arr().eval` to `list.eval` and `list().eval`.
=> Reflect `arr` rename to `list`.

docs/user-guide/concepts/contexts.md
I was reading the documentation and noticed a small typo. This just fixes that.
=> fix typo for groupby

docs/user-guide/expressions/user-defined-functions.md, docs/user-guide/expressions/window.md, docs/user-guide/io/csv.md, docs/user-guide/io/multiple.md, docs/user-guide/lazy/execution.md, docs/user-guide/lazy/query_plan.md, docs/user-guide/lazy/using.md, docs/user-guide/migration/pandas.md, docs/user-guide/misc/alternatives.md, docs/user-guide/misc/multiprocessing.md
Tried to work toward unifying some capitalization.
I moved some of the methods to American English spelling since optimizer is spelled with American English. But if you prefer British English spellings let me know. (In general the docs switch back and forth a lot).
Edited a few sentences for clarity.
=> Some additional fixes for clarity

docs/src/python/user-guide/concepts/contexts.py, docs/src/python/user-guide/concepts/expressions.py, docs/src/python/user-guide/expressions/aggregation.py, docs/src/python/user-guide/expressions/casting.py, docs/src/python/user-guide/expressions/folds.py, docs/src/python/user-guide/expressions/functions.py, docs/src/python/user-guide/expressions/numpy-example.py, docs/src/python/user-guide/expressions/operators.py, docs/src/python/user-guide/expressions/strings.py, docs/src/python/user-guide/expressions/user-defined-functions.py, docs/src/python/user-guide/expressions/window.py, docs/user-guide/migration/pandas.md, docs/user-guide/migration/spark.md
As discussed on Discord.
After https://github.com/pola-rs/polars/issues/6451, parts of the user-guide were not updated with the newer ergonomics. This does not lead to the examples not working, but leads to Polars code looking rather cluttered. In addition, it can lead to user confusion since most Polars code now doesn't have these restrictions. For example:
```py
out = df.select(
[
pl.struct(["keys", "values"])
.apply(lambda x: len(x["keys"]) + x["values"])
.alias("solution_apply"),
(pl.col("keys").str.lengths() + pl.col("values")).alias("solution_expr"),
]
)
```
can and should now be written as:
```py
out = df.select(
pl.struct(["keys", "values"])
.apply(lambda x: len(x["keys"]) + x["values"])
.alias("solution_apply"),
(pl.col("keys").str.lengths() + …
```
=> Update ergonomics across the user-guide

docs/src/python/user-guide/expressions/window.py, docs/src/python/user-guide/transformations/joins.py, docs/src/rust/user-guide/expressions/window.rs, docs/user-guide/expressions/window.md, docs/user-guide/lazy/query_plan.md, docs/user-guide/transformations/time-series/rolling.md
The last example in Expressions / Window functions purports to select the fastest three and the strongest three pokemon for each type, so should perhaps be sorting rows in each group in descending order before picking the first 3.
The last example in Transformations / Joins is meant to demonstrate the effect of `tolerance = "1m"`, but does not actually use this argument.
=> Fixes for examples in the User Guide

docs/user-guide/lazy/execution.md
Address https://github.com/pola-rs/polars/issues/9786.
=> Add a note on reusing LazyFrames

docs/src/rust/getting-started/expressions.rs
So, I tried to implement one of the `TODO` examples for Rust - the expressions filter example (thought it might be easy).
The related python code:
```python
df.filter(
pl.col("c").is_between(datetime(2022, 12, 2), datetime(2022, 12, 8)),
)
```
However, I searched the polars rust and couldn't find an `Expr.is_between` method, and all I could figure out for datetime column comparisons was doing `col("c").dt().datetime()`. I also had to use `lit()` because there's no `From<NaiveDateTime>` for `Expr`s. Does this look right? Is there a better way to do this in rust polars? Based on the docs this is supposed to be the "simple" example but it's ... not.
=> Add rust filter example

API_REFERENCE_LINKS.yaml, docs/index.md, docs/src/python/user-guide/expressions/functions.py, docs/user-guide/expressions/functions.md, docs/user-guide/misc/reference-guides.md, docs/user-guide/sql/select.md
This PR fixes broken references to the now deprecated function `approx_unique`. References in the Polars user guide are updated to the new function `approx_n_unique`. To see where the code currently breaks check this link: https://pola-rs.github.io/polars-book/user-guide/expressions/functions/#count-unique-values
=> fix: update approx_unique function references

docs/src/rust/getting-started/series-dataframes.rs
I thought it confusing to have only the "import chrono" as the start and thought it was a copy/paste issue, so thought I would clarify the comment and explicitly add the "polars" prelude.
I also noticed that upon enabling the feature "describe" the example didn't work unless I use the `{:?}` pretty-print
```
error[E0277]: `Result<polars::prelude::DataFrame, PolarsError>` doesn't implement `std::fmt::Display`
--> src/main.rs:53:20
|
53 |     println!("{}", df.describe(None));
|                    ^^^^^^^^^^^^^^^^^ `Result<polars::prelude::DataFrame, PolarsError>` cannot be formatted with the default formatter
|
= help: the trait `std::fmt::Display` is not implemented for `Result<polars::prelude::DataFrame, PolarsError>`
= note: in format strings you may be able to use `{:?}` (or {:#?} for …
```
=> Clarify required imports, fix default formatter for describe

docs/src/python/user-guide/io/bigquery.py, docs/user-guide/io/bigquery.md
There is currently no documentation for writing polars dataframes to bigquery. This pull request suggests an approach that writes the dataframe as a parquet file to a bytes stream (without saving to disk), and then uses the bigquery API to save the parquet file as a bigquery table.
=> Add documentation for writing polars dataframes to bigquery
